name: auth_weebi
description: "Shared authentication package for Weebi with JWT token management, persistence, and permissions"
version: 1.0.7
homepage: https://weebi.com

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter  # flutter is needed for provider, no need to fantasize about pure Dart

  protos_weebi: ^1.2.6  # Protobuf and gRPC
  
  provider: ^6.1.4   # State management
  flutter_secure_storage: ^9.2.4 # Secure storage for access token when available
  
  # Utilities
  collection: ^1.19.1 # exported

dev_dependencies:
  lints: ^5.0.0
  test: ^1.26.3
