// Mocks generated by Mockito 5.4.6 from annotations
// in boutiques_weebi/test/elegant_boutique_list_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:boutiques_weebi/src/providers/boutique_provider.dart' as _i5;
import 'package:protos_weebi/grpc.dart' as _i3;
import 'package:protos_weebi/grpc.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:protos_weebi/protos_weebi_io.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFenceServiceClient_0 extends _i1.SmartFake
    implements _i2.FenceServiceClient {
  _FakeFenceServiceClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseFuture_1<R> extends _i1.SmartFake
    implements _i3.ResponseFuture<R> {
  _FakeResponseFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientCall_2<Q1, R1> extends _i1.SmartFake
    implements _i4.ClientCall<Q1, R1> {
  _FakeClientCall_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseStream_3<R1> extends _i1.SmartFake
    implements _i3.ResponseStream<R1> {
  _FakeResponseStream_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BoutiqueProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoutiqueProvider extends _i1.Mock implements _i5.BoutiqueProvider {
  MockBoutiqueProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Chain> get chains => (super.noSuchMethod(
        Invocation.getter(#chains),
        returnValue: <_i2.Chain>[],
      ) as List<_i2.Chain>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  _i2.FenceServiceClient get fenceServiceClient => (super.noSuchMethod(
        Invocation.getter(#fenceServiceClient),
        returnValue: _FakeFenceServiceClient_0(
          this,
          Invocation.getter(#fenceServiceClient),
        ),
      ) as _i2.FenceServiceClient);

  @override
  List<_i2.BoutiqueMongo> get allBoutiques => (super.noSuchMethod(
        Invocation.getter(#allBoutiques),
        returnValue: <_i2.BoutiqueMongo>[],
      ) as List<_i2.BoutiqueMongo>);

  @override
  List<_i2.BoutiqueMongo> get activeBoutiques => (super.noSuchMethod(
        Invocation.getter(#activeBoutiques),
        returnValue: <_i2.BoutiqueMongo>[],
      ) as List<_i2.BoutiqueMongo>);

  @override
  Map<_i2.Chain, List<_i2.BoutiqueMongo>> get boutiquesByChain =>
      (super.noSuchMethod(
        Invocation.getter(#boutiquesByChain),
        returnValue: <_i2.Chain, List<_i2.BoutiqueMongo>>{},
      ) as Map<_i2.Chain, List<_i2.BoutiqueMongo>>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.BoutiqueMongo> getBoutiquesForChain(String? chainId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBoutiquesForChain,
          [chainId],
        ),
        returnValue: <_i2.BoutiqueMongo>[],
      ) as List<_i2.BoutiqueMongo>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> loadChains() => (super.noSuchMethod(
        Invocation.method(
          #loadChains,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void selectChain(_i2.Chain? chain) => super.noSuchMethod(
        Invocation.method(
          #selectChain,
          [chain],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectBoutique(_i2.BoutiqueMongo? boutique) => super.noSuchMethod(
        Invocation.method(
          #selectBoutique,
          [boutique],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> createChain(_i2.Chain? chain) => (super.noSuchMethod(
        Invocation.method(
          #createChain,
          [chain],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> updateChain(_i2.ChainRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChain,
          [request],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> deleteChain(String? chainId) => (super.noSuchMethod(
        Invocation.method(
          #deleteChain,
          [chainId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> createBoutique(
    String? chainId,
    _i2.BoutiquePb? boutique, {
    List<int>? logo,
    String? logoExtension,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBoutique,
          [
            chainId,
            boutique,
          ],
          {
            #logo: logo,
            #logoExtension: logoExtension,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> updateBoutique(
    String? chainId,
    String? boutiqueId,
    _i2.BoutiquePb? boutique, {
    List<int>? logo,
    String? logoExtension,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBoutique,
          [
            chainId,
            boutiqueId,
            boutique,
          ],
          {
            #logo: logo,
            #logoExtension: logoExtension,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> deleteBoutique(
    String? chainId,
    String? boutiqueId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBoutique,
          [
            chainId,
            boutiqueId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  List<_i2.BoutiqueMongo> searchBoutiques(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchBoutiques,
          [query],
        ),
        returnValue: <_i2.BoutiqueMongo>[],
      ) as List<_i2.BoutiqueMongo>);

  @override
  List<_i2.Chain> searchChains(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchChains,
          [query],
        ),
        returnValue: <_i2.Chain>[],
      ) as List<_i2.Chain>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FenceServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFenceServiceClient extends _i1.Mock
    implements _i2.FenceServiceClient {
  MockFenceServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ResponseFuture<_i2.SignUpResponse> signUp(
    _i2.SignUpRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.SignUpResponse>(
          this,
          Invocation.method(
            #signUp,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.SignUpResponse>);

  @override
  _i3.ResponseFuture<_i2.Tokens> authenticateWithCredentials(
    _i2.Credentials? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticateWithCredentials,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.Tokens>(
          this,
          Invocation.method(
            #authenticateWithCredentials,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.Tokens>);

  @override
  _i3.ResponseFuture<_i2.Tokens> authenticateWithRefreshToken(
    _i2.RefreshToken? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticateWithRefreshToken,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.Tokens>(
          this,
          Invocation.method(
            #authenticateWithRefreshToken,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.Tokens>);

  @override
  _i3.ResponseFuture<_i2.CreateFirmResponse> createFirm(
    _i2.CreateFirmRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFirm,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.CreateFirmResponse>(
          this,
          Invocation.method(
            #createFirm,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.CreateFirmResponse>);

  @override
  _i3.ResponseFuture<_i2.Firm> readOneFirm(
    _i2.Empty? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readOneFirm,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.Firm>(
          this,
          Invocation.method(
            #readOneFirm,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.Firm>);

  @override
  _i3.ResponseFuture<_i2.PendingUserResponse> createPendingUser(
    _i2.PendingUserRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPendingUser,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.PendingUserResponse>(
          this,
          Invocation.method(
            #createPendingUser,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.PendingUserResponse>);

  @override
  _i3.ResponseFuture<_i2.ReadOneUserResponse> readOneUser(
    _i2.UserId? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readOneUser,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.ReadOneUserResponse>(
          this,
          Invocation.method(
            #readOneUser,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.ReadOneUserResponse>);

  @override
  _i3.ResponseFuture<_i2.UsersPublic> readAllUsers(
    _i2.Empty? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAllUsers,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.UsersPublic>(
          this,
          Invocation.method(
            #readAllUsers,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.UsersPublic>);

  @override
  _i3.ResponseFuture<_i2.StatusResponse> updateOneUser(
    _i2.UserPublic? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOneUser,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.StatusResponse>(
          this,
          Invocation.method(
            #updateOneUser,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.StatusResponse>);

  @override
  _i3.ResponseFuture<_i2.StatusResponse> updateUserPassword(
    _i2.PasswordUpdateRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPassword,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.StatusResponse>(
          this,
          Invocation.method(
            #updateUserPassword,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.StatusResponse>);

  @override
  _i3.ResponseFuture<_i2.StatusResponse> deleteOneUser(
    _i2.UserId? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOneUser,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.StatusResponse>(
          this,
          Invocation.method(
            #deleteOneUser,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.StatusResponse>);

  @override
  _i3.ResponseFuture<_i2.StatusResponse> createOneChain(
    _i2.Chain? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOneChain,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.StatusResponse>(
          this,
          Invocation.method(
            #createOneChain,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.StatusResponse>);

  @override
  _i3.ResponseFuture<_i2.ReadAllChainsResponse> readAllChains(
    _i2.Empty? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAllChains,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.ReadAllChainsResponse>(
          this,
          Invocation.method(
            #readAllChains,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.ReadAllChainsResponse>);

  @override
  _i3.ResponseFuture<_i2.StatusResponse> updateOneChain(
    _i2.ChainRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOneChain,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.StatusResponse>(
          this,
          Invocation.method(
            #updateOneChain,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.StatusResponse>);

  @override
  _i3.ResponseFuture<_i2.StatusResponse> deleteOneChain(
    _i2.DeleteChainRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOneChain,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.StatusResponse>(
          this,
          Invocation.method(
            #deleteOneChain,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.StatusResponse>);

  @override
  _i3.ResponseFuture<_i2.StatusResponse> createOneBoutique(
    _i2.BoutiqueRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOneBoutique,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.StatusResponse>(
          this,
          Invocation.method(
            #createOneBoutique,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.StatusResponse>);

  @override
  _i3.ResponseFuture<_i2.BoutiqueResponse> readOneBoutique(
    _i2.BoutiqueRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readOneBoutique,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.BoutiqueResponse>(
          this,
          Invocation.method(
            #readOneBoutique,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.BoutiqueResponse>);

  @override
  _i3.ResponseFuture<_i2.StatusResponse> updateOneBoutique(
    _i2.BoutiqueRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOneBoutique,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.StatusResponse>(
          this,
          Invocation.method(
            #updateOneBoutique,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.StatusResponse>);

  @override
  _i3.ResponseFuture<_i2.StatusResponse> deleteOneBoutique(
    _i2.BoutiqueRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOneBoutique,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.StatusResponse>(
          this,
          Invocation.method(
            #deleteOneBoutique,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.StatusResponse>);

  @override
  _i3.ResponseFuture<_i2.IsADeviceInChainResponse> isADeviceInChain(
    _i2.ReadDevicesRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isADeviceInChain,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.IsADeviceInChainResponse>(
          this,
          Invocation.method(
            #isADeviceInChain,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.IsADeviceInChainResponse>);

  @override
  _i3.ResponseFuture<_i2.Devices> readDevices(
    _i2.ReadDevicesRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readDevices,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.Devices>(
          this,
          Invocation.method(
            #readDevices,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.Devices>);

  @override
  _i3.ResponseFuture<_i2.CodeForPairingDevice> generateCodeForPairingDevice(
    _i2.ChainIdAndboutiqueId? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateCodeForPairingDevice,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.CodeForPairingDevice>(
          this,
          Invocation.method(
            #generateCodeForPairingDevice,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.CodeForPairingDevice>);

  @override
  _i3.ResponseFuture<_i2.Device> readOnePendingDevice(
    _i2.ReadDeviceBtqRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readOnePendingDevice,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.Device>(
          this,
          Invocation.method(
            #readOnePendingDevice,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.Device>);

  @override
  _i3.ResponseFuture<_i2.CreateDeviceResponse> createDevice(
    _i2.PendingDeviceRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDevice,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.CreateDeviceResponse>(
          this,
          Invocation.method(
            #createDevice,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.CreateDeviceResponse>);

  @override
  _i3.ResponseFuture<_i2.StatusResponse> updateDevicePassword(
    _i2.UpdateDevicePasswordRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDevicePassword,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.StatusResponse>(
          this,
          Invocation.method(
            #updateDevicePassword,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.StatusResponse>);

  @override
  _i3.ResponseFuture<_i2.StatusResponse> deleteOneDevice(
    _i2.DeleteDeviceRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOneDevice,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<_i2.StatusResponse>(
          this,
          Invocation.method(
            #deleteOneDevice,
            [request],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<_i2.StatusResponse>);

  @override
  _i4.ClientCall<Q, R> $createCall<Q, R>(
    _i3.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_2<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i4.ClientCall<Q, R>);

  @override
  _i3.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i3.ClientMethod<Q, R>? method,
    Q? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_1<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseFuture<R>);

  @override
  _i3.ResponseStream<R> $createStreamingCall<Q, R>(
    _i3.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_3<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ResponseStream<R>);
}
