name: accesses_weebi
description: "User access management package for Weebi - allows admins to manage user permissions and access to boutiques/chains"
version: 1.1.0
homepage: https://weebi.com
repository: https://github.com/weebi-app/weebi-client/packages/accesses
issue_tracker: https://github.com/weebi-app/weebi-client/issues

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter
  ###
  # weebi's kitchen below
  protos_weebi: ^1.3.5
  entitlements_weebi: ^1.0.0
  users_weebi: ^1.1.0
  boutiques_weebi: ^1.1.4
  
  provider: ^6.1.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.8.0